Effect follows a convention of using `_tag` to discriminate between errors (and requirements). The `_tag` of an error must be unique; otherwise, TypeScript will not be able to easily discriminate between the errors.

## Manual Implementation of Tagged Errors

You can implement tagged errors manually:

```typescript
class RequestError {
  public readonly _tag = "RequestError";

  constructor(public readonly message: string) {}
}

class ParseError {
  public readonly _tag = "ParseError";

  constructor(public readonly message: string) {}
}
```

To use these errors, simply create an instance and pass it to the error channel:

```typescript
const fetchTodos = Effect.gen(function* () {
  const response = yield* Effect.tryPromise({
    try: () => fetch("https://jsonplaceholder.typicode.com/todos"),
    catch: () => new RequestError("Failed to fetch todos"),
  });

  const todos = yield* Effect.tryPromise({
    try: () => response.json(),
    catch: () => new ParseError("Failed to parse todos"),
  });

  return todos;
});
```

The benefit of this approach is that the `_tag` acts as a discriminator, enabling pattern matching:

```typescript
pipe(
  fetchTodos,
  Effect.catchAll((error) => {
    switch (error._tag) {
      case "RequestError":
        error; // TypeScript can now infer this as RequestError
      // ...
      case "ParseError":
        error; // TypeScript can now infer this as ParseError
      // ...
    }
  })
);
```

## Using Data.TaggedError

To reduce boilerplate, you can use `Data.TaggedError` from Effect:

```typescript
import { Data, Effect } from "effect";

class RequestError extends Data.TaggedError("RequestError") {
  constructor(public readonly message: string) {
    super();
  }
}

class ParseError extends Data.TaggedError("ParseError") {
  constructor(public readonly message: string) {
    super();
  }
}
```

You can omit the constructor if desired, as it's not necessary in JavaScript:

```typescript
class RequestError extends Data.TaggedError("RequestError") {}

class ParseError extends Data.TaggedError("ParseError") {}
```

However, with this approach, you won't be able to pass or access `message`, as it's logically never defined.

To be able to pass a `message` (or really any custom property) to a `Data.TaggedError`, we just need to define the shape of the properties that the error should be constructed with:

```typescript
class RequestError extends Data.TaggedError("RequestError")<{
  readonly message: string
  readonly url: string
  readonly method: "GET" | "POST"
}> {}

const error = new RequestError({
  message: "Uh oh!",
  url: "https://localhost:3000",
  method: "GET"
})
```

## Using catchTag

To handle a specific error, such as recovering only from a `ParseError`, Effect provides `catchTag`:

```typescript
void pipe(
  fetchTodos,
  Effect.catchTag("ParseError", () => Effect.succeed([])),
  Effect.runPromise
);
```

This is why defining a `_tag` is important - it allows `catchTag` to discriminate:

>show type signature

```typescript
export declare const catchTag: {
  // ...
};
```

The first overload simply checks if `E` has a `_tag` property, and if it does, then `K` is constrained to `E["_tag"]`, otherwise, `K` becomes `never`.

```typescript
<K extends E extends { _tag: string; } ? E["_tag"] : never, E, A1, E1, R1>
```

This is why the `_tag` property is very important, as Effect relies on a tag-based discriminated union pattern.

```ts
(k: K, f: (e: Extract<E, { _tag: K; }>) => ...
```

The function parameter `f` takes an argument of type `Extract<E, { _tag: K; }>`, which extracts from `E` only those types where `_tag` is `K`. This allows TypeScript to infer the correct error type in the callback.

We then need to return an `Effect`.

```typescript
(k: K, f: (e: Extract<E, { _tag: K; }>) => Effect<Ai, E1, R1>
```

This allows returning an `Effect.succeed`, an `Effect.fail`, or even an `Effect.gen`. As long as what's returned has the signature `Effect.Effect<A, E, R>`, it's valid.

This enables re-mapping the error to another if desired (e.g., `Effect.fail(new Error())`), or recovering from it (e.g., `Effect.succeed([])`).

## Using catchTags

Effect also provides `catchTags`, which is similar to `catchTag` but allows passing an object where the keys are the `_tag`s and the values are the callbacks:

```typescript
void pipe(
  fetchTodos,
  Effect.catchTags({
    ParseError: () => Effect.succeed([]),
  }),
  Effect.runPromise
);
```

As with `catchTag`, the callbacks must return an `Effect.Effect<A, E, R>`.

It's not mandatory to pass callbacks for all errors. They're optional. In this case, you can handle only `ParseError`. But you can also handle both:

```typescript
void pipe(
  fetchTodos,
  Effect.catchTags({
    ParseError: () => Effect.succeed([]),

    RequestError: (error) => {
      console.log(error.reason);
      return Effect.succeed([]);
    },
  }),
  Effect.runPromise
);
```
